### ISSUE TITLE
React select types as a dev dependency

### ISSUE THREAD

**Issue by shubham-paliwal-fareye** [paljs/ui#109]
Add react-select types as a dev dependency. I have created a branch to fix this issue but I am not able to push that branch.
Please provide a guideline for contribution.
![Screenshot from 2020-08-20 17-07-33](https://user-images.githubusercontent.com/47414595/90765557-cc4b8900-e307-11ea-8fb1-c2558877be50.png)

**Comment by AhmedElywa** [comment]
@shubham-paliwal-fareye I added this package to my dependency to also installed to the user so you can get auto-completion when you use Select component

**Comment by shubham-paliwal-fareye** [comment]
@AhmedElywa  thanks for letting me know. I would love to contribute to this library can you please share the contribution guidelines and roadmap which you have planned for this library.

**Comment by AhmedElywa** [comment]
To be honest I don't have contribution guidelines I working alone in this package from two years ago but all you need to do is Form my repo make your changes and make a pull request will review your pull if it goes goodwill merge and pushes a new release

**Comment by shubham-paliwal-fareye** [comment]
You have done some awesome work.
I have read this library and have some proposals.
1- Storybook setup
2- Use variants from the styled component instead of variables.
3- Add accessibility.
4- Add sizing and breakdowns in theme.

It will be great if you share your thoughts on the roadmap and have any documentation for understanding this library.

**Comment by AhmedElywa** [comment]
yes we have already docs for everything here https://paljs.com/ui/getting-started
also, you can go online with me from this link https://whereby.com/ahmedelywa 
and you can talk to me in twitter https://twitter.com/AhmedElywh

**Comment by shubham-paliwal-fareye** [comment]
Thanks will contact you once I will read all the code.
