### ISSUE TITLE
Some missing features

### ISSUE THREAD

**Issue by khoibv** [paljs/ui#110]
Dear contributors,

I try to using paljs/ui in my project, i like components with styled-components + bootstrap. Thank you for your great contribution.
But i can not found some features as other libraries having.
- Checkbox do not allow to add `ref` (requirement of [react-hook-form](https://react-hook-form.com/get-started/#Registerfields))
- Menu item supports very little capacity of customization. It's hard to add `n` menus at top of sidebar, and `m` menu at bottom of sidebar. I think library need to allow to add some customized css to MenuItem
- I do not like EvaIcon, and want to using FontAwesome as alternative. But no way to do, except clone source code and edit by myself to support FontAwesome.

Versions:
paljs/ui: 1.0.4
paljs/icons: 1.0.4

**Comment by AhmedElywa** [comment]
@khoibv Thanks for your report.

For Checkbox and react-hook-form. you can use [setValue](https://react-hook-form.com/api#setValue).

```ts
import * as React from 'react';
import { useForm } from 'react-hook-form';

const App = () => {
  const { register, handleSubmit, setValue } = useForm();
  const [state, setState] = useState(value);

  const onSubmit = (data) => {
    console.log(data);
  };
  const onChangeHandler = (value: boolean) => {
    setValue('checkbox', value);
    setState(value);
  };

  React.useEffect(() => {
    register({ name: 'checkbox' });
  }, [register]);
  return (
    <form onSubmit={handleSubmit(onSubmit)}>
      <Checkbox
        status="Success"
        onChange={(value) => onChangeHandler(value)}
        checked={!!state}
      />
      <input type="submit" />
    </form>
  );
};
```

For the menu, I think you can use the https://paljs.com/ui/components/menu theme tab to see the theme variables to customize the style.

For `EvaIcon` you are very welcome to add your needs and make a pull request to this repo.
