### ISSUE TITLE
List with multiple columns

### ISSUE THREAD

**Issue by RaJiska** [paljs/ui#111]
The lists seem to handle only values with a single column (the title of the table). Is there a way to make it multi-column ? Or maybe am I using the wrong component ?

**Comment by AhmedElywa** [comment]
I do not understand what you need here.
Do you need to make a table like this?
![image](https://user-images.githubusercontent.com/4535142/101780897-d1735480-3aff-11eb-856b-8699152580ce.png)

**Comment by RaJiska** [comment]
Yjup, this is exactly what I'd need to do ! How did you achieve this ?

**Comment by AhmedElywa** [comment]
I am using [react-table](https://github.com/tannerlinsley/react-table) package and using my theme variables to style it
you can see my code here
https://github.com/paljs/prisma-tools/blob/master/packages/admin/src/PrismaTable/Table/index.tsx#L503

**Comment by RaJiska** [comment]
Thank you very much ! Well this is one amazingly looking table you made there. I won't be able to do something as pretty but having something that matches the theme should suffice for now.

**Comment by AhmedElywa** [comment]
Is there another thing i can do for you now?

**Comment by RaJiska** [comment]
That's all god, thank you again !
