### ISSUE TITLE
Dynamic path

### ISSUE THREAD

**Issue by milinkovitch** [paljs/ui#112]
Hi dear contributors,
Dynamic paths such as "/user/:id" are supported ?
I looked for this feature for 2 hours but I didn't achieve...
Thanks in advance !

EDIT: I'm reoping this issue because I found a solution but acutally the all page is reloading, maybe you know another way
I added this code  :

gatsby-node.js
```
exports.onCreatePage = ({ page, actions }) => {
  const { createPage } = actions;

  if (['/login/', '/register/', '/forgotten-password/', '/reset-password/'].includes(page.path)) {
    page.context.layout = 'auth';
    createPage(page);
  }
  if (page.path.match(/^\/user\/medical-file\//)) {
    page.matchPath = '/user/medical-file/*';
    page.path = '/user/medical-file';
    page.context.isDynamicPath = true;
    createPage(page);
  }
};
```

Layouts/index.tsx 
```
<LayoutColumns>
    <LayoutColumn className="main-content">
      {pageContext.isDynamicPath ? (
        <Router>
          <MedicalFile path="/user/medical-file/:reference" />
        </Router>
      ) : (
        children
      )}
    </LayoutColumn>
  </LayoutColumns>
```

**Comment by AhmedElywa** [comment]
Hi @milinkovitch,

Our project is a UI library. It contains components you can use.

What you look for here is not our options. It depends on your use framework if it GatsbyJS or NextJS or a regular react project with any route package
